[2022-08-01 17:26:09,301] [face01lib.video_capture] [FACE01.py] [WARNING] USBカメラの受信が出来ません
[2022-08-01 17:26:09,302] [face01lib.video_capture] [FACE01.py] [WARNING] 以下のエラーをシステム管理者へお伝えください
[2022-08-01 17:26:09,302] [face01lib.video_capture] [FACE01.py] [WARNING] --------------------
[2022-08-01 17:26:09,303] [face01lib.video_capture] [FACE01.py] [WARNING] NoneType: None

[2022-08-01 17:26:09,303] [face01lib.video_capture] [FACE01.py] [ERROR] USBカメラとの通信に異常が発生しました
NoneType: None
[2022-08-01 17:26:09,304] [face01lib.video_capture] [FACE01.py] [WARNING] --------------------
[2022-08-01 17:26:09,305] [face01lib.video_capture] [FACE01.py] [WARNING] 終了します
[2022-08-06 20:15:03,630] [face01lib.video_capture] [FACE01.py] [INFO] カメラデバイス番号：0
[2022-08-06 21:34:17,837] [face01lib.video_capture] [FACE01.py] [INFO] カメラデバイス番号：0
[2022-08-06 21:38:17,676] [face01lib.video_capture] [FACE01.py] [INFO] カメラデバイス番号：0
